[project]
name = "config"
version = "0.1.0"
description = "配置模块，负责环境变量和全局配置加载。"
requires-python = ">=3.9"
dependencies = [
    "python-dotenv"
]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0"
] 